### ISSUE TITLE
Adyen::HPP::Signature isn't a helper

### ISSUE THREAD

**Issue by lucasgomide** [wvanbergen/adyen#134]
Why that isn't a helper ? For another class implement it.

For example, Adyen::REST::Response, could implement it to check the signature from response. Or maybe the controller that receive the response..

We can uncouple this feature from `Adyen::HPP` ?

**Comment by lucasgomide** [comment]
Maybe you can extract part of that implementation, because the HPP returns the JSON with others fields, another format.. But I think that is possible make a helper yet.

**Comment by wvanbergen** [comment]
Right now, none of the functionality is in helpers. This is because helpers are a Rails-only feature, so I don't want functionality to be available in helpers primarily. Nothing is stopping you from calling methods with the `Adyen::` namsepace frefix included.

I am not against adding helpers as syntactic sugar; feel free to create PRs, as long as they are devoid of any logic and just call one of the underlying methods I am happy.

**Comment by lucasgomide** [comment]
Yeap, of course !!!  Tks

**Comment by lucasgomide** [comment]
@wvanbergen can you review the PR ?

**Comment by wvanbergen** [comment]
It's merged
